server:
  port: 8443
spring:
  application:
    name: primer
  config:
    activate:
      on-profile:
      - prod
  # security:
  #   user:
  #     name: ${SECURITY_USERNAME:jovisco}
  #     password: ${SECURITY_PASSWORD:12345}
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:myusersdb}"
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        '[format_sql]': ${HIBERNATE_FORMAT_SQL:false}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:WARN}
    com:
      jovisco: 
        springsecurity: ${SPRING_SECURITY_LOG_LEVEL:WARN}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread])
      %yellow(%logger{15}) - %msg%n}
