server:
  port: 7070
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:60m}
spring:
  application:
    name: primer
  config:
    import: application_prod.yml
  profiles:
    active: default
  # security:
  #   user:
  #     name: ${SECURITY_USERNAME:jovisco}
  #     password: ${SECURITY_PASSWORD:12345}
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:myusersdb}"
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        '[format_sql]': ${HIBERNATE_FORMAT_SQL:true}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    com:
      jovisco: 
        springsecurity: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread])
      %yellow(%logger{15}) - %msg%n}
